version: '3.7'
# docker network create devops
services:

  common-db:
    image: postgres:14.2
    restart: always
    environment:
      LANG: C.UTF-8
      POSTGRES_PASSWORD: common01x
      POSTGRES_USER: metax
      POSTGRES_DB: metax
    volumes:
      - type: bind
        source: ./data/
        target: /var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - devops-net

  adminer:
    image: adminer
    restart: always
    environment:
      LANG: C.UTF-8
    ports:
      - 18080:8080
    networks:
      - devops-net

networks:
  devops-net:
    external:
      name: devops
  
