version: "3"

services:
  db:
    image: mysql:8.0
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
    restart: always
    networks:
      - devops-net
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: common01x
      LANT: C.UTF-8


  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080
    networks:
      - devops-net

networks:
  devops-net:
    external:
      name: devops